# Generated by Django 2.1.5 on 2024-02-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240212_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
