# Generated by Django 2.1.5 on 2024-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorialcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/category_images/'),
        ),
    ]
