# Generated by Django 2.1.4 on 2024-03-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240220_0817'),
        ('main', '0005_alter_tutorialcategory_category_image'),
    ]

    operations = [
    ]
