# Generated by Django 5.0.3 on 2024-03-05 17:46

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240220_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('tutorial_slug', models.CharField(max_length=200, unique=True)),
                ('tutorial_content', tinymce.models.HTMLField()),
                ('tutorial_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialseries', verbose_name='Series')),
            ],
        ),
    ]
